#
#
# NESS Reloaded v2 Configuration
#
#

#
#
# General settings
#
dev-mode: false

#
#
# Violation handling
#
# What to do when a player is detected
#
violation-handling:
  notify-staff:
    enable: true
    vl: 6
    discord-webhook: ''
    discord-title: 'Anti-Cheat'
    discord-description: '<hacker> maybe is cheating!'
    discord-color: 'RED'
    bungeecord: false
    notification: '&8[&b&lNESS&8]&r&7> &c%PLAYER% &7failed &c%HACK%&7. VL %VL% Details: %DETAILS%'
  cancel:
    enable: true
    vl: 3
  execute-command:
    enable: true
    vl: 20
    command: 'kick %PLAYER% Please Do not use Cheats! If you think this is an error, contact staff'

#
#
# Enabled checks
#
# Comment out a check to disable
#

enabled-checks:
  - 'Aimbot'
  - 'AutoClicker'
  - 'AntiBot'
  - 'AntiBotWhitelist'
  - 'AntiUnicode'
  - 'AntiKb'
  - 'BadPackets'
  - 'Criticals'
  - 'FastEat'
  - 'FastLadder'
  - 'FastPlace'
  - 'ChestESP'
  - 'ChestStealerCheck'
  - 'FlyGhostMode'
  - 'FlyInvalidMove'
  - 'FlyHighJump'
  - 'FlyInvalidJumpMotion'
  - 'FlyInvalidGravity'
  - 'FlyFalseGround'
  - 'GhostHand'
  - 'LiquidInteraction'
  - 'NameExploit'
  - 'InventoryHack'
  - 'Killaura'
  - 'MorePackets'
  - 'NoSlowDownBow'
  - 'NoSlowDownFood'
  - 'NoWeb'
  - 'NameExploit'
  - 'Phase'
  - 'OldMovementChecks'
  - 'ImpossibleBreak'
#  - 'SpeedAir'
  - 'ScaffoldFalseTarget'
  - 'ScaffoldIllegalTarget'
  - 'ScaffoldAngle'

#
# Check name
#
# Description
#
# Performance impact: minimal, low, medium, high
# Effectiveness: medium, high, very high
#

checks:

#
# AutoClick
#
# Caps clicks per second (CPS) at a hard limit, also calculates
# the variance in the user's clicks (constancy) and the variance
# in the variance (constancy super).
#
# Performance impact: Minimal
# Effectiveness: untested
#
  autoclick:
      # Clicks older than this are completely ignored
    total-retention-secs: 32
    # A basic CPS cap
    hard-limit:
      # These are pairs of CPS limits and required time spans
      #
      # If the player's CPS measured over the time span is greater than the CPS limit, a violation is triggered.
      #
      # For example, '16:3' means that if the player's clicks in the past 3 seconds average 16 CPS, trigger a violation.
      cps-and-required-span:
        - '35:2'
    # A more advanced consistency check
    constancy:
      # These are pairs of standard deviation percentages and sample counts
      #
      # The standard deviation is calculated based on the interval between clicks in the sample.
      # The second number in the pair determines the sample size.
      # Then, the standard deviation percentage is calculated as the standard deviation as percent of the average.
      # If this percent is less than the first number in the pair, a violation is triggered.
      #
      # For example, '30:8' means that if the standard deviation in the interval between clicks over a sample
      # of 8 intervals, divided by the average interval, is greater than 30%, trigger a violation.
      deviation-and-sample:
        - '30:10'
      # These are pairs of standard deviation percentages and sample counts
      #
      # These are conceptually similar to the previous. However, this measures the standard deviations between
      # the standard deviations. Thus, it is called the "super deviation".
      superdeviation-and-supersample:
        - '60:10'
      span-millis: 800

#
# LiquidInteraction
#
# Checks to see if a player placed a block against water.
#
# Performance impact: Minimal
# Effectiveness: High
#
  liquidinteraction:
    whitelisted-materials:
      - 'WATER_LILY'
#
# AntiBot
#
# Blocks Bot Attacks which sends a lot of players
#
# Performance impact: Minimal (Use Async Events)
# Effectiveness: High
#
  antibot:
    maxplayers: 15
    message: 'Bot Attack Detected! By NESS Reloaded'
#
# AntiBotWhitelist
#
# Add A Player to the NESS Reloaded Whitelist, so during a bot attack, this player will not be kicked
#
#
  antibotwhitelist:
    minimumseconds: 10
#
# AutoClicker
#
# A Simple Max CPS Check
#
# Performance impact: Minimal
# Effectiveness: Medium
#
  autoclicker:
    maxCPS: 18
#
# BadPackets
#
# Check if a player sends too many position packets
#
# Performance impact: low
# Effectiveness: High
#
  badpackets:
    maxpackets: 1.12
#
# ElytraCheats
#
# Check if a player fly too quickly with elytra
#
# Performance impact: low
# Effectiveness: High
#
  elytracheats:
    maxxzdiff: 1.5
    maxydiff: 1
#
# FastLadder
#
# Check if a player is climing a ladder/vine too fast
#
# Performance impact: low
# Effectiveness: High
#
  fastladder:
    maxdist: 0.155
#
# FastLadder
#
# Check if a player place too many blocks in a seconds
#
# Performance impact: low
# Effectiveness: Medium
#
  fastplace:
    maxblockplaced: 14
#
# Fly
#
# Check if a player is floating / walking/ flying in air
#
# Performance impact: low
# Effectiveness: High
#
  flyinvalidgravity:
    maxinvalidvelocity: 0.9
#
# InventoryHack
#
# Check if a player click an inventory item while he walks
#
# Performance impact: low
# Effectiveness: Very High
#
  inventoryhack:
    maxdist: 0.1
#
# Killaura
#
# Check if a player is using ForceField / ClickAura / Killaura
# This Check detect only some old clients 
#
# Performance impact: low
# Effectiveness: Medium
#
  killaura:
    maxyaw: 357
    minangle: -0.2
    maxreach: 3.6
#
# MorePackets
#
# Check if a player sends too many packets.
# This blocks some Regen, Nuker and some ServerCrasher exploits
#
# Performance impact: low
# Effectiveness: High
#
  morepackets:
    maxpackets: 68
  playeresp:
    minangle: -0.05

# If you change this, you will receive warnings in console
config-version: 1
